### ISSUE TITLE
Invoice demo application "missing" DMN files

### ISSUE THREAD

**Issue by mpp4manu** [camunda/camunda-consulting#19]
I am new to all of this technology so forgive me if I have missed something obvious.
Your last update comment said you added missing DMN files to the Showcase -> English -> Invoice application.  I assume that I should see actual files in the folder as I see them in the Insurance folder.  However, there are none present.
The current Camunda 7.4.0-alpha3-ee bundle that I have installed has what I assume is a pre-loaded example of this application.  I am trying to figure out how to use DMN and this seems like a good example to use, but without the DMN table (file) attached, I'm not sure I'm looking at the right thing.
Please help my ignorance because DMN support is critical to my project.
Thank you.

**Comment by falko** [comment]
You can find the invoice example that ships with the distro at https://github.com/camunda/camunda-bpm-platform/tree/master/examples/invoice
