### ISSUE TITLE
Not able to autologin

### ISSUE THREAD

**Issue by gargvive** [camunda/camunda-consulting#31]
Hi,

I have included the jar file produced by your code in my build path and added authentication filter in web.xml as described by you. But when I try to open http://localhost:8080/camunda/app/tasklist/?auto-login-username=admin then it will redirect me to default login page (http://localhost:8080/camunda/app/tasklist/default/#/login).  Did i miss something ?

**Comment by berndruecker** [comment]
Should work. Did you investigate further, e.g. debugging into the filter to see why it is not Working?

Are you sure the user you are using (admin in this case) has the necessary permissions to access tasklist?

If you are on the login page - but don't login, can you go to  http://localhost:8080/camunda/app/tasklist/ without an additional login?

**Comment by berndruecker** [comment]
I close this issue here, please refer to the http://forum.camunda.org/ if you have any more questions.
