### ISSUE TITLE
showcases/underwriting - CMMN in documentation outdated

### ISSUE THREAD

**Issue by Fabi755** [camunda/camunda-consulting#33]
Hello,
if I'm right the CMMN diagrams of documentation (`README.md`) are outdated. The play symbol is wrong and should moved to other tasks.

Outdated doc images:
- [docs/case.png](https://github.com/camunda/camunda-consulting/blob/master/showcases/underwriting/docs/case.png)
- [docs/process-and-case.png](https://github.com/camunda/camunda-consulting/blob/master/showcases/underwriting/docs/process-and-case.png)

Current diagram in code:
- [src/main/resources/underwriting-case.png](https://github.com/camunda/camunda-consulting/blob/master/showcases/underwriting/src/main/resources/underwriting-case.png)

**Comment by berndruecker** [comment]
You are absolutly right. And diagrams are Trisotech - we should switch to Camunda Modelers Exports.

Fixed the easy parts right away: https://github.com/camunda/camunda-consulting/commit/30c476369d4665ce37a6f95e85432123fe19b738. Not updated the pptx - as I do not have the original file at hand at the moment
