### ISSUE TITLE
Custom query - deserializing variables

### ISSUE THREAD

**Issue by embee1981** [camunda/camunda-consulting#34]
What is the best way to handle deserializing all types of variables?
The docs

https://docs.camunda.org/manual/7.5/examples/tutorials/custom-queries/#custom-mybatis-queries

 for custom queries refer to code that is no longer present and while the new code is alot more concise than what was there previously its still set up to assume simple string variables.

I'd attempted to recreate what the code does to fetch variables by case execution, mapping the variable fields onto VariableInstanceEntity and querying this object via

```
getTypedValue(true);
```
However this fails as in TypedValueField when requesting the VariableSerializer it fail as there is no command context

```
 public static VariableSerializers getSerializers() {
    if (Context.getCommandContext() != null) {
     ....
    } else {
      throw LOG.serializerOutOfContextException();
    }
  }
```

It would seem more correct to go this way to recreate the variables since I'm not familiar with the db structure for the ACT_RU_VARIABLE table (and it has lots of different value columns) and the deserialization would work well for complex types etc.

The old code would have created the command context I believe, whats the correct way to go about executing custom queries from within a command context as of v7.5?

**Comment by berndruecker** [comment]
Best ask in our forum: http://forum.camunda.org/. We are not using the issues here on this project.
I can see your point, but would actually have to dive into the code to get an idea how to solve this best. Please provide a failing test case, as then this gets much easier and faster to do so.

**Comment by embee1981** [comment]
Ok will post on the forums. You may want to re-raise a bug against your docs then as they don't match up with the current example and think have been out of sync since 7.4 :-)

**Comment by berndruecker** [comment]
Sure - feel free to file a JIRA issue for  that: https://app.camunda.com/jira/
