### ISSUE TITLE
Unable to  deploy the example

### ISSUE THREAD

**Issue by vishalcool88** [camunda/camunda-consulting#36]
Hello, I am trying to deploy the external task example and getting error as 

{"type":"RestException","message":"Cannot instantiate process definition video-publishing:1:1575d1f9-fd76-11e6-9a7f-fc4dd43e6964: no decision definition deployed with key 'fileSizeCheck' and tenant-id 'null': decisionDefinition is null"}

Can anyone please tell what i am doing wrtong. Thanks

**Comment by vishalcool88** [comment]
Above issue is with respect to **camunda-consulting/one-time-examples/blog/external-task-example/**

**Comment by felix-mueller** [comment]
@vishalcool88 looks like you are missing the DMN table. you can just create a new DMN Table with that key and you should be good to go

**Comment by felix-mueller** [comment]
I guess we can close this issue then.
