### ISSUE TITLE
Unable to build WAR file

### ISSUE THREAD

**Issue by dikey94** [camunda/camunda-consulting#37]
Hi, I'm trying to build this project. "mvn clean install" gives me:

> [INFO] Scanning for projects...
> Downloading: https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/camunda-bom/7.5.3-ee/camunda-bom-7.5.3-ee.pom
> Downloading: https://repo.maven.apache.org/maven2/org/camunda/bpm/camunda-bom/7.5.3-ee/camunda-bom-7.5.3-ee.pom
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [ERROR] Non-resolvable import POM: Could not find artifact org.camunda.bpm:camunda-bom:pom:7.5.3-ee in camunda-bpm-nexus (https://app.camunda.com/nexus/content/groups/public) @ line 28, column 19
> [ERROR] 'dependencies.dependency.version' for org.camunda.bpm:camunda-engine:jar is missing. @ line 46, column 14
>  @
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]
> [ERROR]   The project org.camunda.consulting.cockpit.plugin:kpioverview:1.0-SNAPSHOT (C:\Users\me\Desktop\KPI\camunda-consulting-master\snippets\camunda-kpi-monitoring-demo\plugin\cockpit-kpi-overview-plugin\pom.xml) has 2 errors
> [ERROR]     Non-resolvable import POM: Could not find artifact org.camunda.bpm:camunda-bom:pom:7.5.3-ee in camunda-bpm-nexus (https://app.camunda.com/nexus/content/groups/public) @ line 28, column 19 -> [Help 2]
> [ERROR]     'dependencies.dependency.version' for org.camunda.bpm:camunda-engine:jar is missing. @ line 46, column 14
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

What can be wrong?

**Comment by falko** [comment]
This was build against the enterprise edition of Camunda BPM. Either add 
the Enterprise Nexus as a repository and provide your company 
credentials in the Maven settings.xml. Or switch to the Community Edition.

**Comment by dikey94** [comment]
Sure, I've missed the "-ee". How can I deploy the plugin if I have .jar file? Thanks.

**Comment by falko** [comment]
Deployment of a Cockpit plugin works by adding the jar to the classpath 
of Cockpit, i.e. WEB-INF/lib of Camunda Webapp.

Some plugin examples and the Maven Archetype for Cockpit plugins have an 
Ant build script to help with that during testing.

**Comment by felix-mueller** [comment]
@dikey94 I guess we can close this issue as it seems it works out for you
